// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: refresh_tokens.sql

package database

import (
	"context"
	"database/sql"
	"time"

	"github.com/google/uuid"
)

const createRefreshToken = `-- name: CreateRefreshToken :one
INSERT INTO refresh_tokens (token, user_id, expires_at)
VALUES ($1, $2, NOW() + INTERVAL '60 days')
RETURNING token, created_at, updated_at, user_id, expires_at, revoked_at
`

type CreateRefreshTokenParams struct {
	Token  string
	UserID uuid.UUID
}

func (q *Queries) CreateRefreshToken(ctx context.Context, arg CreateRefreshTokenParams) (RefreshToken, error) {
	row := q.db.QueryRowContext(ctx, createRefreshToken, arg.Token, arg.UserID)
	var i RefreshToken
	err := row.Scan(
		&i.Token,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.UserID,
		&i.ExpiresAt,
		&i.RevokedAt,
	)
	return i, err
}

const getUserIDFromRefreshToken = `-- name: GetUserIDFromRefreshToken :one
SELECT user_id, revoked_at, expires_at FROM refresh_tokens WHERE token = $1
`

type GetUserIDFromRefreshTokenRow struct {
	UserID    uuid.UUID
	RevokedAt sql.NullTime
	ExpiresAt time.Time
}

func (q *Queries) GetUserIDFromRefreshToken(ctx context.Context, token string) (GetUserIDFromRefreshTokenRow, error) {
	row := q.db.QueryRowContext(ctx, getUserIDFromRefreshToken, token)
	var i GetUserIDFromRefreshTokenRow
	err := row.Scan(&i.UserID, &i.RevokedAt, &i.ExpiresAt)
	return i, err
}

const revokeRefreshToken = `-- name: RevokeRefreshToken :exec
UPDATE refresh_tokens SET revoked_at = NOW(), updated_at = NOW() WHERE token = $1
`

func (q *Queries) RevokeRefreshToken(ctx context.Context, token string) error {
	_, err := q.db.ExecContext(ctx, revokeRefreshToken, token)
	return err
}
